project:
  type: website

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    keep-md: true
  commonmark: default

website:
  repo-actions: [issue]
  page-navigation: true
  search:
    location: navbar
    type: textbox
  navbar:
    background: primary
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/fligt/falnama-dev
          - text: Start Collaborating
            href: https://github.com/fligt/falnama-dev/fork
          - text: Report a Bug
            href: https://github.com/fligt/falnama-dev/issues
  sidebar:
    style: docked
    search: true
    contents:
      - text: Introduction
        href: index.ipynb
      - section: Explorations
        contents: explorations/*
      - section: Explanations
        contents: explanations/*

metadata-files: [nbdev.yml]